- name: bug
  color: d73a4a
  description: Something is not working

- name: enhancement
  color: a2eeef
  description: New feature or improvement request

- name: documentation
  color: 0075ca
  description: Documentation updates

- name: good first issue
  color: 7057ff
  description: Good for first-time contributors

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: ui
  color: fbca04
  description: Frontend and UX related changes

- name: backend
  color: 0e8a16
  description: Backend and API related changes

- name: api
  color: 1d76db
  description: API contract and endpoint changes

- name: auth
  color: c2e0c6
  description: Authentication and authorization

- name: performance
  color: f9d0c4
  description: Performance improvements

- name: testing
  color: bfdadc
  description: Test coverage and QA

- name: priority:low
  color: cfd3d7
  description: Low priority

- name: priority:medium
  color: fbca04
  description: Medium priority

- name: priority:high
  color: d93f0b
  description: High priority
