name: Feature Request
description: Yeni ozellik veya iyilestirme onerisi
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Ozellik onerisi icin tesekkurler.
  - type: input
    id: problem
    attributes:
      label: Problem Nedir?
      description: Hangi ihtiyac veya aci noktasi var?
      placeholder: Quote olustururken sablon secimi yapmak istiyoruz
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Cozum Onerisi
      description: Beklediginiz davranis
      placeholder: Quote ekranina template secici eklensin
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatifler
      description: Dusundugunuz baska cozumler (opsiyonel)
  - type: dropdown
    id: module
    attributes:
      label: Modul
      options:
        - Dashboard
        - Companies
        - Contacts
        - Opportunities
        - Quotes
        - Tasks
        - Tickets
        - Auth
        - UI/UX
        - Other
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Oncelik
      options:
        - Dusuk
        - Orta
        - Yuksek
    validations:
      required: true
